version: "3.9"

services:
  apache_files:
    image: den0303/apache_testy:latest
    container_name: apaches
    networks:
      - my_network
    ports:
      - "8080:8080"
   
  nginx_files:
    image: den0303/nginx_testy:latest
    ports:
      - "80:80"
    depends_on:
      - apache_files
    container_name: nginx
    networks:
      - my_network

networks:
  my_network:
    driver: bridge