version: "3.9"

services:
  apache_files:
    image: den0303/apache_testy:${TAG}
    container_name: apaches
   
  nginx_files:
    image: den0303/nginx_testy:${TAG}
    ports:
      - "80:80"
    depends_on:
      - apache_files
    container_name: nginx
